// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpportunityApi.Data;

#nullable disable

namespace OpportunityApi.Migrations
{
    [DbContext(typeof(OpportunityApiContext))]
    partial class OpportunityApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Models.Opportunity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ErrorQuantity")
                        .HasColumnType("bigint");

                    b.Property<int>("HoursQuantity")
                        .HasColumnType("int");

                    b.Property<long>("LearningLevel")
                        .HasColumnType("bigint");

                    b.Property<int>("OffDutyHours")
                        .HasColumnType("int");

                    b.Property<string>("OutbreakLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SleepTime")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Opportunity");
                });
#pragma warning restore 612, 618
        }
    }
}
